### ISSUE TITLE
Add flutterfire_ui

### ISSUE THREAD

**Issue by aabounegm** [raxysstudios/andax#17]
Add [`flutterfire_ui`](https://pub.dev/packages/flutterfire_ui) and use it to replace [`infinite_scroll_pagination`](https://pub.dev/packages/infinite_scroll_pagination), as well as add proper UI for auth

**Comment by alkaitagi** [comment]
We already implemented new Auth UI. For the scrolling, we use Algolia, which makes the package irrelevant. Maybe this issue can be closed.

**Comment by aabounegm** [comment]
I would still like to use it for the profile page as well, but I agree that the scope of this issue was to simply make use of the library.
