### ISSUE TITLE
Investigate the unresponsive transition in the Innopolis story

### ISSUE THREAD

**Issue by aabounegm** [raxysstudios/andax#58]
_Nursultan Askarbekuly, [4/23/2022 9:55 AM]_
> The first button does not work, even though it is a transition

https://user-images.githubusercontent.com/11016151/165113358-ae733a7f-9e5f-4cdf-8f63-2d2cbd9da480.mp4

**Comment by alkaitagi** [comment]
For some reason the first transition was looking for `cells['node']` value equal to '1' instead of '0'. This didn't occur to me, and so I can't say which interaction made the editor produce this.
