### ISSUE TITLE
Improve the UX of the "views" and "like" chips

### ISSUE THREAD

**Issue by aabounegm** [raxysstudios/andax#75]
In the story preview sheet, two chips are displayed containing the number of views and number of likes. When signed in, the likes chip becomes greyed out but also clickable. The following improvements are to be introduced:
- [ ] Allow tapping the like button even when not signed in (but perhaps redirect to the login screen or show a toast message)
- [ ] Change the colors to indicate the "views" is not clickable (maybe transparent), and to make it clearer when "likes" is toggled or not (perhaps white/blue by default, red when liked?)

**Comment by alkaitagi** [comment]
Elevation is even redundant there and is barely noticeable. Filling the heart icon must be enough.

**Comment by aabounegm** [comment]
Yes, it looks much better. I generally still prefer using red for the liked state, but it's not a big deal. I also agree the elevation is not necessary
