### ISSUE TITLE
Give the typing indicator a message shape

### ISSUE THREAD

**Issue by aabounegm** [raxysstudios/andax#85]
The typing "..." indicator looks more like a loading indicator with the way it appears in the middle of the screen, not associated with any actor. It should be moved to the side and appear as the content of the message to resemble instant messaging platforms (ex: Facebook Messenger) people are already used to.

**Comment by alkaitagi** [comment]
I agree that the current UI is confusing. This is my proposal.

![image](https://user-images.githubusercontent.com/32439229/168295311-126bcbc6-0ba0-4ce0-8ae9-3d14021dfe61.png)

**Comment by aabounegm** [comment]
So the greyed-out message is the one supposedly being typed? If so, it doesn't make sense to show all of its text because then what exactly is still being typed? I would recommend either a simple version of the [typing indicator cookbook](https://docs.flutter.dev/cookbook/effects/typing-indicator) or the [`animated_text_kit` package](https://pub.dev/packages/animated_text_kit#typewriter).

**Comment by aabounegm** [comment]
Understood. I think the typewriter effect from the mentioned package would better mimic the style of games you're talking about. A user who sees the above might think "well, if I can just tap to skip the loading then why load at all?"

**Comment by aabounegm** [comment]
Good point. Not just about the "in progress" state, but both widgets (markdown & typewriter) even accept plain `String`s, not `Widget`s. I don't think it would be easy to integrate them.
