### ISSUE TITLE
Increase the size of the prompt in the beginning of stories

### ISSUE THREAD

**Issue by aabounegm** [raxysstudios/andax#87]
The description in the beginning of stories (ex: "Your mom asked you to buy potatoes" in the potato story) is too small and can be easily missed, even though it might be essential to the flow of the story.
The font size should be increased

**Comment by alkaitagi** [comment]
This is less of a bug and more of a bad story design. There should have been a confirmation prompt (e.g. _"got it"_ chip) after the setup message. Like we've discussed, I'm deleting the potato story. If that's okay, close the issue.
