### ISSUE TITLE
Client offloading

### ISSUE THREAD

**Issue by alkaitagi** [raxysstudios/andax#90]
Some operations that we performs on the client in Dart can be moved into cloud TS functions and invoked with callbacks. Some of them are:

- [ ] Deleting story
- [ ] Liking story (can fix #80 , #63)

I'm sure there're more. Please identify them and add into this issue.

**Comment by alkaitagi** [comment]
Actually, were there any other such areas of excessive backend interaction in the client?

**Comment by aabounegm** [comment]
There might be, but that is not enough reason to move them to a Cloud Function unless we need some security or atomicity guarantees. I didn't check the code for issues other than the abovementioned.
